// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一個等待回答的請求。顯示用的字串(程式、使用者、主機)來自別的程式或伺服器,前端一律經 `revealHidden` 顯示。
 */
export type AgentApprovalRequest = { id: string, key_name: string, key_fingerprint: string, 
/**
 * 發出請求的程式,由外到內(例如 `["claude", "zsh", "ssh"]`);空 = 認不出來。
 */
program_chain: Array<string>, user: string | null, 
/**
 * 顯示用的主機:known_hosts 裡的名稱,找不到名稱就是主機金鑰的指紋;None = 未知的主機(這條連線沒有可信的 session-bind)。
 */
host: string | null, host_fingerprint: string | null, 
/**
 * 視窗可以提供「記住」(spec §5.3)。
 */
rememberable: boolean, remember_minutes: number, needs_passphrase: boolean, 
/**
 * 上一次輸入的 passphrase 不對時的說明。
 */
passphrase_error: string | null, 
/**
 * 已經核准,只需要 passphrase:從 SSHelter 按 Connect(spec §5.6),或剛允許了、記住的 passphrase 卻不對、或上一次輸入的不對。
 */
preapproved: boolean, };
