// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 視窗的回答。
 */
export type AgentApprovalAnswer = { allow: boolean, remember: boolean, passphrase: string | null, remember_passphrase: boolean, };
