// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「Keys used by synced hosts」上方的提示(spec §6、§11)。
 */
export type AgentProblem = { "kind": "not_running", reason: string, } | { "kind": "include_missing" };
