// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatedDirective } from "./GatedDirective";

/**
 * 核准簽章(spec §7.4):兩份文字的簽章相同,代表受管制的設定與它們適用的主機範圍都沒變。
 */
export type ApprovalSignature = { 
/**
 * `Host` 那一行 keyword 之後的整段文字,去頭尾空白:所有 pattern 依原順序,連同行尾註解。
 */
host: string, 
/**
 * 受管制的 directive,依出現順序。
 */
gated: Array<GatedDirective>, };
