// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `sync://approval` 的一項(spec §7.4):這一輪新保留、等待核准的主機。
 */
export type ApprovalNotice = { space_id: string, space_name: string, aliases: Array<string>, };
