// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupInfo = { 
/**
 * Full path to the `.bak` file (in the managed file's mirror dir under the backups root).
 */
path: string, 
/**
 * The managed config file this backup snapshots.
 */
file: string, 
/**
 * Backup timestamp (unix millis, parsed from the `<name>.<millis>.bak` filename).
 */
timestamp_ms: number, };
