// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一台用到候選金鑰的主機。
 */
export type CandidateHost = { alias: string, 
/**
 * 主機所在 space 的名稱(來自帳戶;UI 以 `revealHidden` 顯示)。
 */
space_name: string, 
/**
 * 那一行 `IdentityFile` 目前的值(會被改寫的就是它)。
 */
value: string, 
/**
 * 不改寫的原因(同名主機有不只一份,spec §5);null = 會改寫。
 */
locked: string | null, };
