// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 部署前的環境檢查結果。
 */
export type DeployPreflight = { 
/**
 * 本機 ssh 是否夠新（>= 8.5）可自動填密碼。
 */
askpassSupported: boolean, 
/**
 * 這台 host 的設定是否封鎖了密碼認證。
 */
passwordAuthBlocked: boolean, 
/**
 * 本機是否有可用的密鑰環。false 時密碼只能經環境變數傳給 helper，且無法「記住」。
 */
keychainAvailable: boolean, };
