// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 部署結果。前端據此顯示對應文案。
 */
export type DeployOutcome = { "kind": "added" } | { "kind": "alreadyPresent" } | { "kind": "wrongPassword" } | { "kind": "hostKeyFailed" } | { "kind": "unreachable" } | { "kind": "remoteError", code: number, } | { "kind": "other", message: string, };
