// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DuplicateAlias = { alias: string, 
/**
 * 被遮蔽(ssh 不會用)的那份所在的檔案。
 */
local_file: string, };
