// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 檔案指紋：用於偵測 SSH config 被外部工具（ssh CLI、其他編輯器）改動。
 */
export type Fingerprint = { 
/**
 * 修改時間（unix 毫秒；取不到時為 0）
 */
mtime_ms: number, 
/**
 * 檔案內容的小寫 hex SHA-256
 */
sha256: string, };
