// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一行受管制的設定。
 */
export type GatedDirective = { 
/**
 * keyword 小寫,例如 `proxycommand`。
 */
keyword: string, 
/**
 * keyword 之後的整段文字(含解析器當成行尾註解的部分),去頭尾空白。
 */
value: string, };
