// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * host key 的三種狀態（外加「掃不到」）。
 */
export type HostKeyStatus = { "kind": "trusted" } | { "kind": "new", fingerprint: string, key_line: string, } | { "kind": "mismatch", fingerprint: string, } | { "kind": "unavailable", message: string, };
