// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostSummary = { 
/**
 * First pattern token, used as the primary identifier in the UI.
 */
alias: string, patterns: Array<string>, 
/**
 * The ConfigFile path as a string (lossy UTF-8).
 */
source_file: string, 
/**
 * Parsed from a `#group:` sentinel comment in the host body.
 */
group: string | null, 
/**
 * Parsed from a `#tags:` sentinel comment in the host body.
 */
tags: Array<string>, };
