// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostOption } from "./HostOption";

export type HostDetail = { alias: string, patterns: Array<string>, source_file: string, tags: Array<string>, 
/**
 * Every body Directive in order (comments and blanks are skipped).
 */
options: Array<HostOption>, };
