// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostSummary = { 
/**
 * First pattern token, used as the primary identifier in the UI.
 */
alias: string, patterns: Array<string>, 
/**
 * The ConfigFile path as a string (lossy UTF-8).
 */
source_file: string, 
/**
 * Parsed from a `#tags:` sentinel comment in the host body.
 */
tags: Array<string>, 
/**
 * First enabled `HostName` value, if any — for a meaningful, distinct list subtitle.
 */
hostname: string | null, 
/**
 * First enabled `User` value, if any.
 */
user: string | null, };
