// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncOverview } from "./SyncOverview";

/**
 * 從檔案加進 SSHelter 之後(`local_keys::import_file`):改指到新插槽的主機、原檔移除了沒、Move 卻留下原檔的原因。
 */
export type ImportResult = { overview: SyncOverview, slot_id: string, rewritten_hosts: Array<string>, removed_file: boolean, file_kept: string | null, };
