// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 之前的帳戶留下的插槽(`KeyCandidate.kept_slot`;`kept_lookup`):離開帳戶之後建立或加入了另一個帳戶,`~/.ssh/sshelter-local/` 裡用到它的主機
 * 又被搬進新帳戶的 space。新帳戶裡沒有它(N1:不會自己寫進去),要不要放進去由使用者在這裡決定。
 */
export type KeptSlot = { 
/**
 * 插槽 id;放進帳戶之後也是它。
 */
id: string, 
/**
 * 插槽檔名(`<name>-<id8>`):用到它的主機照舊指著 `~/.ssh/sshelter/keys/<file_name>`。
 */
file_name: string, 
/**
 * 插槽裡是這台在之前的帳戶裡同步來的副本;否則連到這台的一把金鑰。
 */
synced_copy: boolean, };
