// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帳戶裡沒有、這台留著的插槽(`KeyCandidate.kept_slot`;`kept_lookup`),用到它的主機在同步的 space 裡 —— 要不要放進這個帳戶由使用者在這裡決定。兩種:
 * 之前的帳戶留下的插槽(離開帳戶之後建立或加入了另一個帳戶,`~/.ssh/sshelter-local/` 裡用到它的主機又被搬進新帳戶的 space;新帳戶裡沒有它,
 * N1:不會自己寫進去),與只在這台的金鑰(`local_only`:New key 或 Generate key 加進 SSHelter 的,不在任何帳戶裡)。
 */
export type KeptSlot = { 
/**
 * 插槽 id;放進帳戶之後也是它。
 */
id: string, 
/**
 * 插槽檔名(`<name>-<id8>`):用到它的主機照舊指著 `~/.ssh/sshelter/keys/<file_name>`。
 */
file_name: string, 
/**
 * 插槽裡是這台在之前的帳戶裡同步來的副本(檔案);否則是連到這台的一把金鑰,或在保管庫裡的金鑰(`in_vault`)。
 */
synced_copy: boolean, 
/**
 * 金鑰在這台的保管庫裡(`SlotSource::Vault`):沒有私鑰檔,候選的 `path` 是插槽路徑,Sync key 從保管庫讀。
 */
in_vault: boolean, 
/**
 * 只在這台的金鑰(`LocalSlot::local_only`),不是之前的帳戶留下的。
 */
local_only: boolean, };
