// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 可以產生的金鑰種類。
 */
export type KeyAlgorithm = "ed25519" | "rsa3072" | "rsa4096" | "ecdsa_p256";
