// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateHost } from "./CandidateHost";
import type { KeptSlot } from "./KeptSlot";

/**
 * 一把用在同步主機上、還沒有插槽的本機金鑰(或可以直接沿用的插槽)。
 */
export type KeyCandidate = { 
/**
 * 這台電腦上金鑰檔的完整路徑(`IdentityFile` 解析出來的)。之前的帳戶留下的插槽(`kept_slot`)是它的金鑰:連到的金鑰檔,或插槽裡同步來的副本;
 * 金鑰在這台保管庫裡的(`KeptSlot::in_vault`)沒有私鑰檔,是插槽路徑(主機指的就是它)。
 */
path: string, 
/**
 * 預設的插槽名稱:金鑰檔名;之前的帳戶留下的插槽與只在這台的金鑰是它們自己的名稱(不能改)。
 */
default_name: string, fingerprint: string | null, has_passphrase: boolean | null, 
/**
 * 不能同步的原因(只能 Keep on this computer);null = 可以同步。
 */
unsyncable: string | null, 
/**
 * 已經有這把金鑰的插槽:這台建立或挑過、連到同一個檔案的,金鑰在這台保管庫裡、指紋相同的,或帳戶裡同指紋的 `synced` 插槽(spec §6.1 第 1 步:直接
 * 沿用,不再詢問)。和帳戶裡另一個插槽同檔名、這台又沒有握著的插槽在這台不能用,不列在這裡。
 */
existing_slot: string | null, hosts: Array<CandidateHost>, 
/**
 * 之前的帳戶留下的插槽(spec §7.1),或只在這台的金鑰(金鑰保管庫 spec §4.3,`KeptSlot::local_only`):「Sync key」與「Keep on this computer」把它就地放進
 * 這個帳戶(`adopt_slot`),不建立新插槽、不改名。金鑰檔是同一個的有好幾個插槽時(連到金鑰檔的,或同步來的副本),是掃描時先遇到的那一個,用到其他那些的主機改指到它;
 * 金鑰在保管庫裡的(`KeptSlot::in_vault`)沒有金鑰檔可以認出是同一把,每個插槽各是一個候選。null = 不是。
 */
kept_slot: KeptSlot | null, };
