// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateHost } from "./CandidateHost";

/**
 * 一把用在同步主機上、還沒有插槽的本機金鑰(或可以直接沿用的插槽)。
 */
export type KeyCandidate = { 
/**
 * 這台電腦上金鑰檔的完整路徑(`IdentityFile` 解析出來的)。
 */
path: string, default_name: string, fingerprint: string | null, has_passphrase: boolean | null, 
/**
 * 不能同步的原因(只能 Keep on this computer);null = 可以同步。
 */
unsyncable: string | null, 
/**
 * 已經有這把金鑰的插槽:這台建立或挑過、連到同一個檔案的,或帳戶裡同指紋的 `synced` 插槽(spec §6.1 第 1 步:直接
 * 沿用,不再詢問)。和帳戶裡另一個插槽同檔名、這台又沒有握著的插槽在這台不能用,不列在這裡。
 */
existing_slot: string | null, hosts: Array<CandidateHost>, };
