// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyCandidate } from "./KeyCandidate";
import type { UnsupportedIdentity } from "./UnsupportedIdentity";

export type KeyCandidates = { keys: Array<KeyCandidate>, unsupported: Array<UnsupportedIdentity>, };
