// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyDecision } from "./KeyDecision";

export type KeyChoice = { 
/**
 * `KeyCandidate.path`。
 */
path: string, decision: KeyDecision, };
