// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 使用者對一把金鑰的決定。
 */
export type KeyDecision = { "kind": "sync", name: string, } | { "kind": "keep", name: string, } | { "kind": "reuse", slot_id: string, };
