// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 選了金鑰檔之後的預覽(`local_keys::preview_file`)。`problem` = 加不進去的原因。
 */
export type KeyFilePreview = { default_name: string, fingerprint: string | null, key_type: string | null, has_passphrase: boolean | null, 
/**
 * Move into SSHelter 會改的主機:每一個 `IdentityFile` 指到這個檔案的 Host 區塊(萬用字元的 Host 也算),名稱是區塊的第一個 pattern,依出現順序、不重複。
 * 來自 config,畫面以 `revealHidden` 顯示。
 */
hosts: Array<string>, 
/**
 * 檔案是 `ssh` 沒寫 `IdentityFile` 時會試的 `~/.ssh/id_*`(移走之後那些主機找不到它)。
 */
default_identity: boolean, problem: string | null, };
