// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityFileInfo } from "./IdentityFileInfo";

export type KeyHygiene = { identity_files: Array<IdentityFileInfo>, identities_only: boolean, explicit: boolean, };
