// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One keypair found in ~/.ssh. Identification fields (type/bits/fingerprint/comment) come
 * from `ssh-keygen -l` and are best-effort: a failure leaves them None/"unknown" instead of
 * failing the whole listing.
 */
export type KeyInfo = { name: string, private_path: string, public_path: string | null, 
/**
 * e.g. "ED25519", "RSA"; "unknown" when `ssh-keygen -l` failed.
 */
key_type: string, bits: number | null, fingerprint_sha256: string | null, comment: string | null, 
/**
 * Loaded into the running ssh-agent (matched by SHA256 fingerprint).
 */
in_agent: boolean, };
