// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One known_hosts entry for the UI. `line_index` addresses the file line (stable as long as the
 * file is unchanged — guarded by the expected-hosts check on removal).
 */
export type KnownHostEntry = { line_index: number, 
/**
 * First field verbatim: comma-joined host names, or the `|1|…` hash for hashed entries.
 */
hosts: string, key_type: string, 
/**
 * `SHA256:<base64-no-padding>` of the key blob (OpenSSH format); None if the blob is not
 * valid base64.
 */
fingerprint_sha256: string | null, hashed: boolean, 
/**
 * `@revoked` / `@cert-authority` when present.
 */
marker: string | null, };
