// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LintIssue = { 
/**
 * Stable kebab-case rule id (e.g. "duplicate-directive") so the frontend can toggle rules.
 */
rule: string, severity: string, file: string, alias: string | null, keyword: string | null, message: string, };
