// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpAuditEntry = { id: string, alias: string, command: string, outcome: string, exit_code: number | null, detail: string | null, completed_at_ms: number, };
