// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpPendingRequest = { id: string, alias: string, command: string, hostname: string | null, user: string | null, port: string | null, requested_at_ms: number, };
