// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAuditEntry } from "./McpAuditEntry";
import type { McpPendingRequest } from "./McpPendingRequest";

export type McpStatus = { enabled: boolean, bridge_active: boolean, allowed_hosts: Array<string>, pending: Array<McpPendingRequest>, recent: Array<McpAuditEntry>, executable: string, last_client_at_ms: number | null, };
