// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationFailure } from "./MigrationFailure";

export type MigrationReport = { moved: Array<string>, failed: Array<MigrationFailure>, tagged: number, };
