// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「Move」搬不進保管庫的一把(金鑰保管庫 spec §8):插槽 id、名稱(來自帳戶,畫面以 `revealHidden` 顯示)與原因。
 */
export type MoveFailure = { slot_id: string, name: string, message: string, };
