// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveFailure } from "./MoveFailure";
import type { SyncOverview } from "./SyncOverview";

/**
 * 「Move」做完的結果:最新的狀態,與搬不進去的那些。
 */
export type MoveIntoVaultResult = { overview: SyncOverview, failed: Array<MoveFailure>, };
