// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 建檔計畫:UI 據此即時顯示「會建立在哪、會不會動 main config」。
 */
export type NewFilePlan = { 
/**
 * 實際會建立的完整路徑。
 */
path: string, 
/**
 * 命中的既有 Include pattern(None = 需要插入 Include 行)。
 */
coveredBy: string | null, 
/**
 * 將插入 main config 的 Include「值」(covered_by 為 Some 時為 None)。
 */
includeValue: string | null, 
/**
 * 依 glob 字尾補齊後的最終檔名。
 */
finalName: string, 
/**
 * 目標路徑已存在(由 command 層以檔案系統回填;純函式一律 false)。
 */
alreadyExists: boolean, };
