// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncOverview } from "./SyncOverview";

/**
 * New key / Generate key 之後:最新狀態與新插槽的 id(畫面選到它)。
 */
export type NewKeyResult = { overview: SyncOverview, slot_id: string, };
