// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「一個來源檔建立一個 space」(spec §7.2)的一組:新 space 的名稱(UI 以來源檔名產生,檔名 alias 優先)與要搬進去的主機。
 */
export type NewSpaceGroup = { name: string, aliases: Array<string>, };
