// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalSignature } from "./ApprovalSignature";

/**
 * 一筆等待核准的主機(`sync_pending_approvals`;spec §7.4、§8 的審核對話框)。
 */
export type PendingApprovalView = { space_id: string, space_name: string, alias: string, 
/**
 * 這一版的內容指紋(`spaces::review_digest`):核准 / 拒絕時連同 `alias` 送回(`ReviewedVersion`)—— 只處理使用者看過的
 * 這一版。序號與版本號都可能指到別的內容(relay 的歷史倒退、兩台寫出同一個版本號),所以以內容認。
 */
digest: string, 
/**
 * 要套用的完整區塊。
 */
text: string, 
/**
 * 目前 space 檔裡的區塊;None = 這台還沒有這台主機。
 */
current_text: string | null, 
/**
 * 目前區塊與新區塊的核准簽章(UI 標出受管制的行與差異)。
 */
applied: ApprovalSignature, incoming: ApprovalSignature, from_device: string, updated_at_ms: number, };
