// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncOverview } from "./SyncOverview";

/**
 * `sync_approve` / `sync_reject` 的結果(spec §7.4)。
 */
export type ReviewOutcome = { 
/**
 * 實際處理了幾台:核准 = 套用的主機數,拒絕 = 丟棄的版本數。
 */
applied: number, 
/**
 * 略過的主機:使用者看過的版本已經不是待核准的那一版(被較新的取代、已處理或已不在清單上)。較新的版本留在清單上;
 * UI 顯示「已變更,請重新確認」並重新讀 `sync_pending_approvals`。
 */
changed: Array<string>, 
/**
 * 動作之後的最新狀態(同其他 command 回傳的 `SyncOverview`)。
 */
overview: SyncOverview, };
