// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 審核對話框送回的一筆(`sync_approve` / `sync_reject`):使用者看過的那一版 —— `PendingApprovalView` 的 `alias` 與 `digest`。
 */
export type ReviewedVersion = { alias: string, digest: string, };
