// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更換同步碼走到哪一步(spec §7.5 的編號)。
 */
export type RotationStep = "prepared" | "local_changes_sent" | "freezing" | "copying" | "deleting" | "switching";
