// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 插槽在這台電腦上的狀態(SP3 spec §7.2、§7.3)。
 */
export type SlotStatusView = { "kind": "ready", file: string, synced_copy: boolean, fingerprint: string | null, } | { "kind": "needs_key", waiting_for_sync: boolean, } | { "kind": "not_in_use", file: string, } | { "kind": "not_used_here" } | { "kind": "synced_available", file: string, } | { "kind": "source_changed", file: string, } | { "kind": "error", message: string, };
