// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Suggestion = { name: string, host_name: string, port: number | null, 
/**
 * "known_hosts" | "tailscale"
 */
source: string, online: boolean | null, };
