// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `sync://conflict` 的一項(spec §7.1 第 8 步):這台未上傳的修改被別台較新的版本取代。
 */
export type SyncConflict = { space_id: string, space_name: string, aliases: Array<string>, };
