// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RotationStep } from "./RotationStep";

/**
 * 這台正在更換同步碼(spec §7.5)。
 */
export type SyncRotationView = { step: RotationStep, 
/**
 * 只有第 3 步(凍結)之前可以取消。
 */
cancellable: boolean, 
/**
 * 建立 chain 被限流:暫停到這個時間後自動接續。
 */
paused_until_ms: number | null, };
