// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帳戶裡的一個 space(spec §8),依 Include 清單的順序。
 */
export type SyncSpaceView = { id: string, name: string, 
/**
 * 這台有勾選(同步下來成為一個檔案)。
 */
selected: boolean, 
/**
 * 勾選時的檔名與完整路徑(`~/.ssh/sshelter/<slug>-<id8>.config`)。
 */
file_name: string | null, file_path: string | null, 
/**
 * 勾選時的主機數;沒勾選的 space 這台不知道。
 */
hosts: number | null, pending_uploads: number, approvals: number, 
/**
 * 剛勾選、第一輪(基線輪)還沒完成:這段期間不要搬主機進來。
 */
first_sync_pending: boolean, 
/**
 * relay 上的 chain 不見了、帳戶卻仍有它(spec §9):提供「重建」或「刪除」。
 */
missing: boolean, 
/**
 * 只屬於這個 space 的錯誤(違反不變式、寫入失敗)。
 */
last_error: string | null, created_at_ms: number, 
/**
 * 勾選了這個 space 的裝置名稱。
 */
synced_on: Array<string>, };
