// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最近一次 `GET /v1/info`(spec §6.4、§8)。
 */
export type SyncRelayView = { url: string, 
/**
 * relay 回報的版本;None = 舊版 relay(沒有 `GET /v1/info`)。
 */
version: string | null, 
/**
 * 有批次查詢;false → 逐條查詢,UI 提示「relay 可以更新」。
 */
batch_pull: boolean, 
/**
 * 有凍結;false → 「更換同步碼」停用並說明要先更新 relay。
 */
freeze: boolean, };
