// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotDeviceView } from "./SlotDeviceView";
import type { SlotMode } from "./SlotMode";
import type { SlotStatusView } from "./SlotStatusView";

/**
 * 一個金鑰插槽(SP3 spec §7.2),依名稱排序。
 */
export type SyncKeySlotView = { id: string, 
/**
 * 插槽名稱;來自別台電腦,UI 以 `revealHidden` 顯示。
 */
name: string, mode: SlotMode, 
/**
 * `synced` 的金鑰指紋;`own` 為 null。
 */
fingerprint: string | null, key_type: string | null, has_passphrase: boolean | null, 
/**
 * 建立插槽的電腦名稱。
 */
origin_device: string, origin_is_this: boolean, 
/**
 * 主機 `IdentityFile` 的值(`~/.ssh/sshelter/keys/<file>`)。
 */
value: string, 
/**
 * 這台用到它的主機。
 */
hosts: Array<string>, status: SlotStatusView, 
/**
 * 其他電腦的插槽狀況(它們的 `device.slots`)。
 */
devices: Array<SlotDeviceView>, };
