// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDevice } from "./SyncDevice";

export type SyncStatus = { joined: boolean, 
/**
 * chain id 前 8 個 hex,只作辨識用。
 */
chain_short: string | null, device_id: string, device_name: string, relay_url: string, last_sync_ms: number | null, last_error: string | null, 
/**
 * 尚未上傳的記錄數。
 */
pending: number, read_only: boolean, devices: Array<SyncDevice>, managed_file: string, hosts_in_sync: number, 
/**
 * Leave 之後助記詞還留在 keychain(刪除失敗):UI 顯示警示與重試。
 */
phrase_cleanup_pending: boolean, };
