// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDeviceView } from "./SyncDeviceView";
import type { SyncFrozenView } from "./SyncFrozenView";
import type { SyncKeySlotView } from "./SyncKeySlotView";
import type { SyncNotice } from "./SyncNotice";
import type { SyncRelayView } from "./SyncRelayView";
import type { SyncRotationView } from "./SyncRotationView";
import type { SyncSpaceView } from "./SyncSpaceView";

/**
 * Settings → Sync 的全部狀態(`sync_overview` 與 `sync://status`)。
 */
export type SyncOverview = { joined: boolean, 
/**
 * 帳戶 chain id 的前 8 個 hex,只作辨識。
 */
account_short: string | null, device_id: string, device_name: string, relay_url: string, relay: SyncRelayView | null, last_sync_ms: number | null, last_error: string | null, 
/**
 * 帳戶用了比這版新的格式:只讀,不上傳。
 */
read_only: boolean, 
/**
 * v1 升級還沒完成(spec §7.6)。
 */
upgrading: boolean, frozen: SyncFrozenView | null, rotation: SyncRotationView | null, devices: Array<SyncDeviceView>, spaces: Array<SyncSpaceView>, pending_uploads: number, approvals_waiting: number, 
/**
 * `~/.ssh/sshelter/` 裡不在 Include 清單上的 `.config` 檔:OpenSSH 不讀,只提示(spec §4.3)。
 */
stray_files: Array<string>, 
/**
 * 帳戶裡的金鑰插槽與這台還留著副本的舊插槽(SP3 spec §7.2)。
 */
key_slots: Array<SyncKeySlotView>, 
/**
 * 等使用者看過的提示,`sync_dismiss_notice(index)` 清掉。
 */
notices: Array<SyncNotice>, 
/**
 * 離開帳戶時同步碼刪不掉:顯示警示與重試。
 */
phrase_cleanup_pending: boolean, };
