// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 帳戶裡的一台裝置(spec §8)。Forget 只是從清單移除,不是撤權。
 */
export type SyncDeviceView = { id: string, name: string, platform: string, joined_at_ms: number, last_seen_ms: number, is_this: boolean, 
/**
 * 這台裝置勾選的 space id。
 */
spaces: Array<string>, };
