// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 這台偵測到同步碼已被更換(spec §7.5):請使用者輸入新同步碼。
 */
export type SyncFrozenView = { detected_at_ms: number, 
/**
 * 更換了同步碼的裝置名稱;空 = 還只知道 relay 拒絕了上傳。兩個以上 = 多台同時更換,輸入其中一組即可。
 */
by_devices: Array<string>, };
