// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncDevice = { id: string, name: string, platform: string, joined_at_ms: number, last_seen_ms: number, is_this: boolean, };
