// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A terminal emulator we can launch into.
 */
export type TerminalInfo = { id: string, label: string, };
