// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A terminal emulator we can launch into.
 */
export type TerminalInfo = { id: string, label: string, 
/**
 * Whether this terminal supports opening the connection in a NEW TAB of an existing window.
 * Only iTerm2 qualifies: Terminal.app's only new-tab path is System Events GUI scripting,
 * which requires the user to grant Accessibility permission — explicitly NOT doing that.
 * All Linux emulators are launched as new windows, so they are `false` as well.
 */
supports_new_tab: boolean, };
