// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `IdentityFile` 的值無法自動設定的主機(§5)。
 */
export type UnsupportedIdentity = { alias: string, value: string, reason: string, };
