// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下載進度事件。格式同 plugin 自己的 `DownloadEvent`(tag = "event"、content = "data"、欄位 camelCase),
 * 前端兩個頻道才能用同一套處理顯示下載進度。
 */
export type UpdateDownloadEvent = { "event": "Started", "data": { contentLength: number | null, } } | { "event": "Progress", "data": { chunkLength: number, } } | { "event": "Finished" };
