// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 給前端的更新摘要,對應 plugin JS `Update` 的 version / body。
 */
export type UpdateInfo = { version: string, body: string | null, };
